name: 'Storybook Tests'
on: push

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          npm install
          npm install @storybook/addon-coverage --save-dev
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      
      - name: Build Storybook
        run: npm run build-storybook --quiet
      
      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && npm run test-storybook -- --coverage --maxWorkers=2"

      - name: Generate Coverage Report
        run: |
          npx nyc report --reporter=lcov -t coverage/storybook --report-dir coverage/storybook-lcov
          npx nyc report --reporter=text -t coverage/storybook
        
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: storybook-coverage
          path: coverage/